quiz/config/urls.py
from django.contrib import admin
from django.urls import path, include

from users import views
from users.views import logout_view

app_name = "main"

urlpatterns = [
    path("", views.index, name="homepage"),
    path('users/', include('users.urls', namespace="users")),
    path('admin/', admin.site.urls),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path('logout', logout_view, name="logout")

]

quiz/users/urls.py
from django.urls import path

from .views import index, savol_detail, logout_view, create_question, check_answer

app_name = "users"
urlpatterns = [
    path('', index, name="home"),
    path('savol-detail/<int:id>/', savol_detail, name="savol_detail"),
    path('logout', logout_view, name="logout"),
    path('create-question/', create_question, name="create_question"),
    path('check-answer/<int:id>/', check_answer, name="check_answer"),
   
]

quiz/accounts/models.py
from django.db import models

# Create your models here.

quiz/users/models.py
import datetime

from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)

    @admin.display(
        boolean=True,
        ordering='oub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

    class Book(models.Model):
        book_title = models.CharField(max_length=150)
        publication_year = models.IntegerField()
        author = models.CharField(max_length=100)
        plot = models.TextField()

        def __str__(self):
            return self.book_title


class Task(models.Model):
    ...

    class Meta:
        permissions = [
            ("change_task_status", "Can change the status of tasks"),
            ("close_task", "Can remove a task by setting its status as closed"),
        ]


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=100)

quiz/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ['pub_date']


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

quiz/accounts/views.py
from django.shortcuts import render

# Create your views here.

quiz/users/views.py
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewUserForm, QuestionForm
from .models import Question, Choice


def register_request(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registation successful. ")
            return redirect("homepage")
        messages.error(request, "Unsuccessful registration.Invalid information")
    form = NewUserForm()
    return render(request=request, template_name="register.html", context={"register_form": form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now login in as{username}.")
                return redirect("homepage")
            else:
                messages.error(request, "Invalid username or password. ")
    else:
        messages.error(request, "Invalid username or password.")
        form = AuthenticationForm()
    return render(request=request, template_name="login.html", context={"login_form": form})


def index(request):
    print(request.user)
    savollar = Question.objects.all()
    return render(request, 'users/index.html', {'savollar': savollar})


def savol_detail(request, id):
    savol = get_object_or_404(Question, id=id)
    return render(request, 'users/detail.html', {"savol": savol})


def logout_view(request):
    logout(request)
    return redirect('login')


@login_required
def create_question(request):
    form = QuestionForm()
    if request.method == "POST":
        form = QuestionForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:home")
    return render(request, 'users/question_form.html', {"form": form})


def check_answer(request, id):
    variant = get_object_or_404(Choice, id=id)
    # to'g'rimi yo'qmi tekshirib, natijalar tablitsasiga saqlaymiz
    question_ids = list(Question.objects.values_list('id', flat=True))
    try:
        next_question_id = question_ids[question_ids.index(variant.question.id) + 1]
    except Exception as e:
        print(e)
        next_question_id = None
    if next_question_id:
        return redirect("users:savol_detail", id=next_question_id)

        score = 0
        wrong = 0
        correct = 0
        total = 0
        for q in questions:
            total += 1
            print(request.POST.get(q.question))
            print(q.ans)
            print()
            if q.ans == request.POST.get(q.question):
                score += 10
                correct += 1
            else:
                wrong += 1
        percent = score / (total * 10) * 100
        context = {
            'score': score,
            'time': request.POST.get('timer'),
            'correct': correct,
            'wrong': wrong,
            'percent': percent,
            'total': total
        }
        return render(request, 'users/result.html', context)
    else:
        questions = Question.objects.all()
        context = {
            'questions': questions
        }
        return render(request, 'users/checked.html', {'correct': variant.is_correct})

quiz/users/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/users/templates/style.css">

</head>
<body>


<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
<!--          <a class="nav-link active" aria-current="page" href="{% url 'users:home' %}">Questions</a>-->
          <a class="nav-link" aria-current="page"  href="{% url 'users:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container mt-4">
    {% block content %}

    {% endblock %}
</div>


<link rel="stylesheet" type="text/css" href="{% static 'users/style.css' %}">
</body>

</html>

quiz/users/templates/login.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>LOGIN</title>
</head>
{% extends "users/index.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Login-->
<div class="container py-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {{ login_form|crispy }}
        <button class="btn btn-primary mt5" type="submit">Login</button>
    </form>
    <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p>
</div>

{% endblock %}

<div class="mx-auto" style="width: 500px" >
    <form action="login_user" method="post" class="form-horizontal">
        {% csrf_token%}
        <div class="col-xs-8 col-xs-offset-4">
            <h2 style="text-align:center;">LOGIN</h2>
        </div>

        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Enter Username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password">
        </div>
        <button type="submit" class="btn btn-primary">LOGIN</button>
        <br/>
        <div class="form-group">
            {% for message in messages %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endfor %}
        </div>
    </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
</div>
</body>
</html>

quiz/users/templates/register.html
{% extends "users/index.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<h1>Register</h1>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">Login</a> instead.</p>
</div>

{% endblock %}

quiz/users/templates/users/checked.html
{% extends 'base.html' %}

{% block content %}
<h1>Test yakunlandi!</h1>

{% endblock %}

quiz/users/templates/users/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Savol: {{ savol.question_text }}</h1>
    <ul class="list-group">
        {% for choice in savol.choice_set.all %}
        <li class="list-group-item">{{ forloop.counter }}.
            <a href="{% url 'users:check_answer' id=choice.id %}">{{ choice.choice_text }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

quiz/users/templates/users/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Savollar</h1>
    <ul class="list-group">
        {% for question in savollar %}
        <li class="list-group-item">{{ forloop.counter }}.
            <a href="{% url 'users:savol_detail' id=question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% if request.user.is_authenticated %}
<a href="{% url 'users:create_question' %}" class="btn btn-primary my-3">Yangi savol yaratish</a>
{% endif %}
{% endblock %}

quiz/users/templates/users/question_form.html
{% extends "users/index.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<h1>Create Question</h1>
	<form action="." method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		<button class="btn btn-primary my-3" type="submit">Save</button>
	</form>
</div>

{% endblock %}

quiz/users/templates/users/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>